
[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip', 'postgresql', 'bash']

[phases.install]
cmds = ['pip install --no-cache-dir -r requirements.txt']

[start]
cmd = 'bash railway_start.sh'
