
[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip', 'python310Packages.virtualenv', 'postgresql', 'bash']
cmds = ['python -m venv /opt/venv']

[phases.install]
cmds = ['/opt/venv/bin/pip install --no-cache-dir -r requirements.txt']

[start]
cmd = 'source /opt/venv/bin/activate && bash railway_start.sh'
