
[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip', 'postgresql']

[phases.install]
cmds = ['pip install --no-cache-dir -r requirements.txt']

[phases.build]
cmds = ['python init_db.py']

[start]
cmd = 'python stunning_dashboard.py'
